---
version: '3.8'

services:
  web:
    build: .
    container_name: 'flask_api'
    ports: 
      - 5000:5000
    volumes:
      - .:/home/code/
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    command: /bin/bash -c "flask run --host=0.0.0.0"
