"""empty message

Revision ID: 36c1d5f975cc
Revises: 
Create Date: 2021-02-18 20:40:41.021560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c1d5f975cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('did_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=True),
    sa.Column('monthy_price', sa.Float(precision=(8, 2), asdecimal=True), nullable=True),
    sa.Column('setup_price', sa.Float(precision=(8, 2), asdecimal=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('did_number')
    # ### end Alembic commands ###
